let b = 2;
try{
    let a = b + 2;
}catch(erro)
{
    console.log(erro);
}